CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  firstname TEXT NOT NULL,
  lastname TEXT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  birthdate TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  ip TEXT NOT NULL,
  user_agent TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 1,
  write INTEGER NOT NULL DEFAULT 1,
  manage INTEGER NOT NULL DEFAULT 1,
  admin INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expire_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS gateways (
  id TEXT PRIMARY KEY,
  home_id TEXT NOT NULL REFERENCES homes (id) ON DELETE CASCADE,
  name TEXT,
  model TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id TEXT NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS homes (
  id TEXT PRIMARY KEY,
  name TEXT,
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id TEXT NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS rooms (
  id TEXT PRIMARY KEY,
  name TEXT,
  icon TEXT,
  home_id TEXT NOT NULL REFERENCES homes (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id TEXT NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS devices (
  id TEXT PRIMARY KEY,
  gateway_id TEXT NOT NULL REFERENCES gateways (id),
  name TEXT,
  physical_id TEXT NOT NULL,
  physical_name TEXT NOT NULL,
  plugin TEXT NOT NULL,
  room_id TEXT NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id TEXT NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS permissions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users (id),
  type TEXT NOT NULL,
  type_id TEXT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  write INTEGER NOT NULL DEFAULT 0,
  manage INTEGER NOT NULL DEFAULT 0,
  admin INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS automations (
  id TEXT PRIMARY KEY,
  home_id TEXT NOT NULL REFERENCES homes (id) ON DELETE CASCADE,
  name TEXT,
  trigger TEXT[],
  trigger_key TEXT[],
  trigger_value TEXT[],
  trigger_operator TEXT[],
  action TEXT[],
  action_call TEXT[],
  action_value TEXT[],
  status BOOL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator_id TEXT NOT NULL REFERENCES users (id)
);
